### PR TITLE
v1.5.2

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Ideally, we would merge this to a throwaway branch.  If someone from @conda-forge/flask-admin wants to create one, I'll be happy to change the destination.

I need this particular version for [airflow v1.10.2](https://github.com/conda-forge/airflow-feedstock/pull/24)

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge/core, this is the second time in an hour where I've had trouble rerendering.  Is something a bit wonky right now?

**Comment by ocefpaf** [comment]
We have a new version of conda-smithy and the webservices probably require an update. Can you do a local re-render for now? (I'm looking into the webservice problem.)

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Thanks @ocefpaf.  I'm about to head out so I'll just wait.  Just wanted to check.

**Comment by xylar** [comment]
Thanks again, @ocefpaf

**Pull request merged**
